### ISSUE TITLE
[Bug]: Alt text pulling from filename, not image_alt attribute 

### ISSUE THREAD

**Issue by honor-gfsc** [geeksforsocialchange/two-towers#102]
## Description

Image alt text is pulling the filename, not the image_alt attribute 

<img width="523" alt="Screenshot 2023-04-11 at 16 58 58" src="https://user-images.githubusercontent.com/127757676/231221100-c8213510-affd-43f2-acfe-1bb1bc3d5f3e.png">

**Comment by aaaaargZombies** [comment]
see Rosies screenshot for verification
