### ISSUE TITLE
Timeline items link to sources (where present)

### ISSUE THREAD

**Issue by honor-gfsc** [geeksforsocialchange/two-towers#114]
## Description

Timeline items should have a mechanism of linking to image or news sources. Some items will have a hyperlink specified in the markdown as 'link'

## Acceptance Criteria

- [ ] Timeline items have a clickable link to the source 'link' attribute where present 
- [ ] This is signed off by @undividual design wise

**Comment by aaaaargZombies** [comment]
https://github.com/geeksforsocialchange/two-towers/assets/6824891/c5b887f9-726d-4c59-8446-e98355e2fa04
