### ISSUE TITLE
[Bug]: Fix jaggy bits on edge of provided project logo

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/two-towers#119]
<img width="368" alt="Screenshot 2023-04-12 at 17 12 47" src="https://user-images.githubusercontent.com/511734/231518423-90cdd2aa-deaa-4793-b396-692e53a0c3ad.png">

as ivan noted, there's little white sticky out bits on the side of the logo

**Comment by aaaaargZombies** [comment]
![image](https://github.com/geeksforsocialchange/two-towers/assets/6824891/b56c9905-d5a7-41b0-81e4-4daeee72fe53)
