### ISSUE TITLE
[Bug]: Paragraph spacing on about page is huge

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/two-towers#120]
<img width="1042" alt="Screenshot 2023-04-12 at 17 13 40" src="https://user-images.githubusercontent.com/511734/231518632-829931d1-80ac-403c-a1de-b38c39453016.png">

this looks massive spacing to me!

**Comment by aaaaargZombies** [comment]
![image](https://github.com/geeksforsocialchange/two-towers/assets/6824891/e0e852dd-35e5-4627-bdae-e221ec6eb84c)
