### ISSUE TITLE
Basic accessibility review

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/two-towers#122]
## Description
Run down accessibility checklist to make sure we're doing all the right things. Obviously we will be accessibility first as we build but it's worthwhile to do an audit after we have built a few pages.

### Must do: 
- [x] Run something like lighthouse (https://developer.chrome.com/docs/lighthouse/overview/)
- [x] Use a WAVE tool to evaluate each page https://wave.webaim.org/
- [x] Run through site use with keyboard only
- [x] #169
- [x] Check all meaningful images for alt text
- [x] Check all form inputs for labels
- [x] Check all links for meaningful & unique link text
- [x] Check all headings are correct for thier semantic meaning

### Should do:
- [ ] #168

## Notes
- Starling bank has a nice statement https://www.starlingbank.com/website-accessibility. We ought to be doing all the things listed there as "What we are doing"

**Comment by aaaaargZombies** [comment]
verification evidence is the tickets made and listed in the comments above
