### ISSUE TITLE
Fix issues with refs to MA student Sam

### ISSUE THREAD

**Issue by undividual** [geeksforsocialchange/two-towers#123]
## Description
On the 'about' page, it's Sam **Benbow**, not Bembow
Can you also put, "University of York Cultural Heritage Managment MA student Sam Benbow"

## Plan

Make these amends to the text

## Acceptance criteria
The copy is now correct

**Comment by aaaaargZombies** [comment]
![image](https://github.com/geeksforsocialchange/two-towers/assets/6824891/a8d9bba9-0303-4b67-a124-0ede83a2ac0e)
