### ISSUE TITLE
A timeline item has a contributor data attribute

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/two-towers#140]
In order to support filtering, user content needs an extra attribute defining who the content was created from. Similar to the `data-type` attribute.

(Something in the md file meta data?)

## Acceptance criteria

- [ ] a data attribute for contributors exists on the same element as the existing `data-type` attribute
- [ ] it covers all named "storytellers"  but not external resources like Wikipedia or news

## implementation details

existing data attribute location
https://github.com/geeksforsocialchange/two-towers/blob/main/layouts/partials/timeline.html#L32

contributor list
https://github.com/geeksforsocialchange/two-towers/blob/main/content/about/index.md?plain=1#L32

**Comment by aaaaargZombies** [comment]
![2023-05-24-160255_1920x1080_scrot](https://github.com/geeksforsocialchange/two-towers/assets/6824891/e3cb445f-d1fd-4963-a40c-a8ee924138a8)
