### ISSUE TITLE
[Bug]: When clicking the share button while using a screenreader, the text asserting the link has been copied is not read

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/two-towers#171]
## Description

We should probably add a more descriptive aria-label to the share button to explain what clicking it does, or we should find out how to make the screen reader read the copy message after clicking the button

## Steps to reproduce

- [ ] add alert aria role to pop up message
- [ ] ask Rosie nicely to test it works as desired

## Platform (if relevant)

What device and browser were you using?

**Comment by aaaaargZombies** [comment]
https://github.com/geeksforsocialchange/two-towers/assets/6824891/258fc6ad-ed21-4565-aeca-2ea46a7420f1
